/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as HostEventRouteImport } from './routes/host-event'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MentorCommandCenterRouteImport } from './routes/mentor-command-center'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfileOverviewRouteImport } from './routes/profile-overview'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminEvaluationsRouteImport } from './routes/admin.evaluations'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminHackathonsRouteImport } from './routes/admin.hackathons'
import { Route as AdminJudgesRouteImport } from './routes/admin.judges'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMentorsRouteImport } from './routes/admin.mentors'
import { Route as AdminProblemsRouteImport } from './routes/admin.problems'
import { Route as AdminRecruitmentRouteImport } from './routes/admin.recruitment'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AdminHackathonsCreateRouteImport } from './routes/admin.hackathons.create'
import { Route as HackathonsIdRegisterRouteImport } from './routes/hackathons.$id.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventRoute = HostEventRouteImport.update({
  id: '/host-event',
  path: '/host-event',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCommandCenterRoute = MentorCommandCenterRouteImport.update({
  id: '/mentor-command-center',
  path: '/mentor-command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOverviewRoute = ProfileOverviewRouteImport.update({
  id: '/profile-overview',
  path: '/profile-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvaluationsRoute = AdminEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHackathonsRoute = AdminHackathonsRouteImport.update({
  id: '/hackathons',
  path: '/hackathons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJudgesRoute = AdminJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsRoute = AdminProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecruitmentRoute = AdminRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHackathonsCreateRoute = AdminHackathonsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminHackathonsRoute,
} as any)
const HackathonsIdRegisterRoute = HackathonsIdRegisterRouteImport.update({
  id: '/hackathons/$id/register',
  path: '/hackathons/$id/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/certificates': typeof CertificatesRoute
  '/challenge': typeof ChallengeRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/host-event': typeof HostEventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/mentor-command-center': typeof MentorCommandCenterRoute
  '/payment': typeof PaymentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/profile-overview': typeof ProfileOverviewRoute
  '/recruitment': typeof RecruitmentRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/evaluations': typeof AdminEvaluationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hackathons': typeof AdminHackathonsRouteWithChildren
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hackathons/create': typeof AdminHackathonsCreateRoute
  '/hackathons/$id/register': typeof HackathonsIdRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/certificates': typeof CertificatesRoute
  '/challenge': typeof ChallengeRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/host-event': typeof HostEventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/mentor-command-center': typeof MentorCommandCenterRoute
  '/payment': typeof PaymentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/profile-overview': typeof ProfileOverviewRoute
  '/recruitment': typeof RecruitmentRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/evaluations': typeof AdminEvaluationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hackathons': typeof AdminHackathonsRouteWithChildren
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/hackathons/create': typeof AdminHackathonsCreateRoute
  '/hackathons/$id/register': typeof HackathonsIdRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/certificates': typeof CertificatesRoute
  '/challenge': typeof ChallengeRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/evaluations': typeof EvaluationsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/host-event': typeof HostEventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/mentor-command-center': typeof MentorCommandCenterRoute
  '/payment': typeof PaymentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/profile-overview': typeof ProfileOverviewRoute
  '/recruitment': typeof RecruitmentRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sponsors': typeof SponsorsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/timeline': typeof TimelineRoute
  '/workspace': typeof WorkspaceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/evaluations': typeof AdminEvaluationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hackathons': typeof AdminHackathonsRouteWithChildren
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hackathons/create': typeof AdminHackathonsCreateRoute
  '/hackathons/$id/register': typeof HackathonsIdRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/ai-assistant'
    | '/certificates'
    | '/challenge'
    | '/code-of-conduct'
    | '/community'
    | '/dashboard'
    | '/evaluations'
    | '/faq'
    | '/gallery'
    | '/highlights'
    | '/host-event'
    | '/leaderboard'
    | '/login'
    | '/mentor'
    | '/mentor-command-center'
    | '/payment'
    | '/privacy-policy'
    | '/problems'
    | '/profile'
    | '/profile-overview'
    | '/recruitment'
    | '/register'
    | '/settings'
    | '/sponsors'
    | '/support'
    | '/team'
    | '/timeline'
    | '/workspace'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/evaluations'
    | '/admin/gallery'
    | '/admin/hackathons'
    | '/admin/judges'
    | '/admin/leaderboard'
    | '/admin/logs'
    | '/admin/mentors'
    | '/admin/problems'
    | '/admin/recruitment'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/teams'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/admin/'
    | '/admin/hackathons/create'
    | '/hackathons/$id/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/ai-assistant'
    | '/certificates'
    | '/challenge'
    | '/code-of-conduct'
    | '/community'
    | '/dashboard'
    | '/evaluations'
    | '/faq'
    | '/gallery'
    | '/highlights'
    | '/host-event'
    | '/leaderboard'
    | '/login'
    | '/mentor'
    | '/mentor-command-center'
    | '/payment'
    | '/privacy-policy'
    | '/problems'
    | '/profile'
    | '/profile-overview'
    | '/recruitment'
    | '/register'
    | '/settings'
    | '/sponsors'
    | '/support'
    | '/team'
    | '/timeline'
    | '/workspace'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/evaluations'
    | '/admin/gallery'
    | '/admin/hackathons'
    | '/admin/judges'
    | '/admin/leaderboard'
    | '/admin/logs'
    | '/admin/mentors'
    | '/admin/problems'
    | '/admin/recruitment'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/teams'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/admin'
    | '/admin/hackathons/create'
    | '/hackathons/$id/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/ai-assistant'
    | '/certificates'
    | '/challenge'
    | '/code-of-conduct'
    | '/community'
    | '/dashboard'
    | '/evaluations'
    | '/faq'
    | '/gallery'
    | '/highlights'
    | '/host-event'
    | '/leaderboard'
    | '/login'
    | '/mentor'
    | '/mentor-command-center'
    | '/payment'
    | '/privacy-policy'
    | '/problems'
    | '/profile'
    | '/profile-overview'
    | '/recruitment'
    | '/register'
    | '/settings'
    | '/sponsors'
    | '/support'
    | '/team'
    | '/timeline'
    | '/workspace'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/evaluations'
    | '/admin/gallery'
    | '/admin/hackathons'
    | '/admin/judges'
    | '/admin/leaderboard'
    | '/admin/logs'
    | '/admin/mentors'
    | '/admin/problems'
    | '/admin/recruitment'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/teams'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/admin/'
    | '/admin/hackathons/create'
    | '/hackathons/$id/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AiAssistantRoute: typeof AiAssistantRoute
  CertificatesRoute: typeof CertificatesRoute
  ChallengeRoute: typeof ChallengeRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationsRoute: typeof EvaluationsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HighlightsRoute: typeof HighlightsRoute
  HostEventRoute: typeof HostEventRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  MentorCommandCenterRoute: typeof MentorCommandCenterRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProblemsRoute: typeof ProblemsRoute
  ProfileRoute: typeof ProfileRoute
  ProfileOverviewRoute: typeof ProfileOverviewRoute
  RecruitmentRoute: typeof RecruitmentRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SponsorsRoute: typeof SponsorsRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TimelineRoute: typeof TimelineRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  HackathonsIdRegisterRoute: typeof HackathonsIdRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-event': {
      id: '/host-event'
      path: '/host-event'
      fullPath: '/host-event'
      preLoaderRoute: typeof HostEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-command-center': {
      id: '/mentor-command-center'
      path: '/mentor-command-center'
      fullPath: '/mentor-command-center'
      preLoaderRoute: typeof MentorCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-overview': {
      id: '/profile-overview'
      path: '/profile-overview'
      fullPath: '/profile-overview'
      preLoaderRoute: typeof ProfileOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluations': {
      id: '/admin/evaluations'
      path: '/evaluations'
      fullPath: '/admin/evaluations'
      preLoaderRoute: typeof AdminEvaluationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hackathons': {
      id: '/admin/hackathons'
      path: '/hackathons'
      fullPath: '/admin/hackathons'
      preLoaderRoute: typeof AdminHackathonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/judges': {
      id: '/admin/judges'
      path: '/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof AdminJudgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problems': {
      id: '/admin/problems'
      path: '/problems'
      fullPath: '/admin/problems'
      preLoaderRoute: typeof AdminProblemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recruitment': {
      id: '/admin/recruitment'
      path: '/recruitment'
      fullPath: '/admin/recruitment'
      preLoaderRoute: typeof AdminRecruitmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hackathons/create': {
      id: '/admin/hackathons/create'
      path: '/create'
      fullPath: '/admin/hackathons/create'
      preLoaderRoute: typeof AdminHackathonsCreateRouteImport
      parentRoute: typeof AdminHackathonsRoute
    }
    '/hackathons/$id/register': {
      id: '/hackathons/$id/register'
      path: '/hackathons/$id/register'
      fullPath: '/hackathons/$id/register'
      preLoaderRoute: typeof HackathonsIdRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminHackathonsRouteChildren {
  AdminHackathonsCreateRoute: typeof AdminHackathonsCreateRoute
}

const AdminHackathonsRouteChildren: AdminHackathonsRouteChildren = {
  AdminHackathonsCreateRoute: AdminHackathonsCreateRoute,
}

const AdminHackathonsRouteWithChildren = AdminHackathonsRoute._addFileChildren(
  AdminHackathonsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminEvaluationsRoute: typeof AdminEvaluationsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHackathonsRoute: typeof AdminHackathonsRouteWithChildren
  AdminJudgesRoute: typeof AdminJudgesRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminProblemsRoute: typeof AdminProblemsRoute
  AdminRecruitmentRoute: typeof AdminRecruitmentRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminEvaluationsRoute: AdminEvaluationsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHackathonsRoute: AdminHackathonsRouteWithChildren,
  AdminJudgesRoute: AdminJudgesRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminProblemsRoute: AdminProblemsRoute,
  AdminRecruitmentRoute: AdminRecruitmentRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AiAssistantRoute: AiAssistantRoute,
  CertificatesRoute: CertificatesRoute,
  ChallengeRoute: ChallengeRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  EvaluationsRoute: EvaluationsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HighlightsRoute: HighlightsRoute,
  HostEventRoute: HostEventRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  MentorCommandCenterRoute: MentorCommandCenterRoute,
  PaymentRoute: PaymentRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProblemsRoute: ProblemsRoute,
  ProfileRoute: ProfileRoute,
  ProfileOverviewRoute: ProfileOverviewRoute,
  RecruitmentRoute: RecruitmentRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SponsorsRoute: SponsorsRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TimelineRoute: TimelineRoute,
  WorkspaceRoute: WorkspaceRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  HackathonsIdRegisterRoute: HackathonsIdRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
