/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MentorCommandCenterRouteImport } from './routes/mentor-command-center'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfileOverviewRouteImport } from './routes/profile-overview'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorCommandCenterRoute = MentorCommandCenterRouteImport.update({
  id: '/mentor-command-center',
  path: '/mentor-command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOverviewRoute = ProfileOverviewRouteImport.update({
  id: '/profile-overview',
  path: '/profile-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenge': typeof ChallengeRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mentor': typeof MentorRoute
  '/mentor-command-center': typeof MentorCommandCenterRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/profile-overview': typeof ProfileOverviewRoute
  '/recruitment': typeof RecruitmentRoute
  '/team': typeof TeamRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenge': typeof ChallengeRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mentor': typeof MentorRoute
  '/mentor-command-center': typeof MentorCommandCenterRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/profile-overview': typeof ProfileOverviewRoute
  '/recruitment': typeof RecruitmentRoute
  '/team': typeof TeamRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenge': typeof ChallengeRoute
  '/gallery': typeof GalleryRoute
  '/highlights': typeof HighlightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mentor': typeof MentorRoute
  '/mentor-command-center': typeof MentorCommandCenterRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/profile-overview': typeof ProfileOverviewRoute
  '/recruitment': typeof RecruitmentRoute
  '/team': typeof TeamRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/challenge'
    | '/gallery'
    | '/highlights'
    | '/leaderboard'
    | '/mentor'
    | '/mentor-command-center'
    | '/problems'
    | '/profile'
    | '/profile-overview'
    | '/recruitment'
    | '/team'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/challenge'
    | '/gallery'
    | '/highlights'
    | '/leaderboard'
    | '/mentor'
    | '/mentor-command-center'
    | '/problems'
    | '/profile'
    | '/profile-overview'
    | '/recruitment'
    | '/team'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/challenge'
    | '/gallery'
    | '/highlights'
    | '/leaderboard'
    | '/mentor'
    | '/mentor-command-center'
    | '/problems'
    | '/profile'
    | '/profile-overview'
    | '/recruitment'
    | '/team'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChallengeRoute: typeof ChallengeRoute
  GalleryRoute: typeof GalleryRoute
  HighlightsRoute: typeof HighlightsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MentorRoute: typeof MentorRoute
  MentorCommandCenterRoute: typeof MentorCommandCenterRoute
  ProblemsRoute: typeof ProblemsRoute
  ProfileRoute: typeof ProfileRoute
  ProfileOverviewRoute: typeof ProfileOverviewRoute
  RecruitmentRoute: typeof RecruitmentRoute
  TeamRoute: typeof TeamRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-command-center': {
      id: '/mentor-command-center'
      path: '/mentor-command-center'
      fullPath: '/mentor-command-center'
      preLoaderRoute: typeof MentorCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-overview': {
      id: '/profile-overview'
      path: '/profile-overview'
      fullPath: '/profile-overview'
      preLoaderRoute: typeof ProfileOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChallengeRoute: ChallengeRoute,
  GalleryRoute: GalleryRoute,
  HighlightsRoute: HighlightsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MentorRoute: MentorRoute,
  MentorCommandCenterRoute: MentorCommandCenterRoute,
  ProblemsRoute: ProblemsRoute,
  ProfileRoute: ProfileRoute,
  ProfileOverviewRoute: ProfileOverviewRoute,
  RecruitmentRoute: RecruitmentRoute,
  TeamRoute: TeamRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
